# Warning: This file is generated automatically, and should not be modified.
# Instead, please modify the template in the pr-checks directory and run:
#     pip install ruamel.yaml && python3 sync.py
# to regenerate this file.

name: PR Check - Debug artifact upload
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GO111MODULE: auto
on:
  push:
    branches:
    - main
    - v1
  pull_request:
    types:
    - opened
    - synchronize
    - reopened
    - ready_for_review
  workflow_dispatch: {}
jobs:
  debug-artifacts:
    strategy:
      matrix:
        version:
        - stable-20201028
        - stable-20210319
        - stable-20210809
        - cached
        - latest
        - nightly-latest
        os: [ubuntu-latest, macos-latest]
    name: Debug artifact upload
    permissions:
      security-events: write
    runs-on: ${{ matrix.os }}
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Prepare test
      id: prepare-test
      uses: ./.github/prepare-test
      with:
        version: ${{ matrix.version }}
    - uses: ./../action/init
      with:
        tools: ${{ steps.prepare-test.outputs.tools-url }}
        debug: true
        debug-artifact-name: my-debug-artifacts
        debug-database-name: my-db
    - name: Build code
      shell: bash
      run: ./build.sh
    - uses: ./../action/analyze
      id: analysis
    - uses: actions/download-artifact@v2
      with:
        name: my-debug-artifacts-${{ matrix.os }}-${{ matrix.version }}
    - shell: bash
      run: |
        LANGUAGES="cpp csharp go java javascript python"
        for language in $LANGUAGES; do
          echo "Checking $language"
          if [[ ! -f "$language.sarif" ]] ; then
            echo "Missing a SARIF file for $language"
            exit 1
          fi
          if [[ ! -f "my-db-$language.zip" ]] ; then
            echo "Missing a database bundle for $language"
            exit 1
          fi
          if [[ ! -d "$language/log" ]] ; then
            echo "Missing logs for $language"
            exit 1
          fi
        done
    env:
      INTERNAL_CODEQL_ACTION_DEBUG_LOC: true
